---
title: "Evolution de la population, de la production de nourriture et de l'énergie par continent depuis (1961 - 2020)"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(tidyselect)
library(countrycode)

```


-----------------------------------------------------------------------

# Energie

### Evolution de la production d'energie par continent depuis 1961

```{r fig.width=10}

energy<-read_delim("owid-energy-data__OWID.csv")

seqTp_energy <- energy |> 
  select(1:3,contains("consumption")) |>
  filter(year >= 1961 & year <= 2020) |> 
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation") |> 
  mutate(types = case_when(str_detect(type_energie,"coal|gas|oil")~"fossil_fuel_consumption",
                                 str_detect(type_energie,"nuclear|biofuel|hydro|other_renewable|solar|wind")~"low_carbon_consumption",
                           TRUE~NA_character_)) |> 
   mutate(sources_energy = case_when(str_detect(type_energie,"biofuel")~"biofuel",
                                      str_detect(type_energie,"coal")~"coal",
                                      str_detect(type_energie,"wind")~"wind",
                                      str_detect(type_energie,"gas")~"gas",
                                      str_detect(type_energie,"hydro")~"hydro",
                                      str_detect(type_energie,"solar")~"solar",
                                    str_detect(type_energie,"nuclear")~"nuclear",
                                    str_detect(type_energie,"oil")~"oil",
                                    str_detect(type_energie,"other_renewable")~"other_renewable_consumption"
                                    ))
energy_continent<- seqTp_energy |>
  mutate(continent=countrycode(country, origin = "country.name", destination = "continent"))|>
  rename(annee="year") |> 
  mutate(annee=(as.numeric(annee))) |> 
  drop_na(continent) |> 
  drop_na(types)
    
ggplot(energy_continent )+
  aes(annee,consommation,fill=continent)+
  geom_col()+
  facet_grid(~types)+
     labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))




```



-----------------------------------------------------------------------

### Evolution de la production d'energie par continent et par sources d'energies depuis 1961
```{r fig.width=10}

ggplot(energy_continent )+
  aes(annee,consommation,fill=sources_energy)+
  geom_col()+
  facet_grid(~continent)+
  labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

```



-----------------------------------------------------------------------

# Nourriture

###  Evolution de la production de nourriture par continent depuis 1961

```{r fig.width=10}

food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |> 
  select(-ends_with("F")) |> 
  pivot_longer(cols=Y1961:Y2020,
               names_to="annee",
               values_to="Production_norriture") |> 
  mutate(annee=parse_number(annee)) |> 
  mutate(continent=countrycode(Area, origin = "country.name", destination = "continent")) |> 
  drop_na(continent)

food_continent <-food |> 
  filter(Element=="Production") |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))

ggplot(food_continent)+
  aes(annee,Production_norriture,colour=continent, fill=continent)+
  geom_col()+
  labs(x="Annee", y="Production de norriture (tonnes)")+
  theme(axis.text.x=element_text(size=12,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=12,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))


```


-----------------------------------------------------------------------

### Evolution de la production de nourriture par continent et par item de nourriture depuis 1961
```{r fig.width=10}

ggplot(food_continent )+
  aes(annee,Production_norriture,fill=Item)+
  geom_col()+
  facet_grid(~continent)+
  labs(x="Annee", y="Production de norriture (tonnes)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))
```


# Population

### Evolution de la population par continent depuis 1961

```{r fig.width=8 }
population<- read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv", skip=16,  na="...")

population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx", skip = 16, na="...") |>
  select(1:3, Type,"1950":"2020" )  |>
  pivot_longer(cols=5:75,
               names_to ="annee",
               values_to = "population") |>
  mutate(population=population*1000) |>
  rename(region=3) |> 
  filter(annee>=1961)

population_continent<-population |>
  select(annee, population, region) |> 
  mutate(continent=countrycode(region, origin = "country.name", destination = "continent"))



ggplot(population_continent |> 
         mutate(annee=(as.numeric(annee))) |> 
         drop_na(continent)) +
  aes(annee, population,fill=continent) +
  geom_col()+
  scale_x_continuous( trans='log10') +
  scale_y_continuous(labels=function(x) {
    format(x,scientific=FALSE,
           big.mark=" ")
    
  })

```

