---
title: "Evolution de la population, de la production de nourriture et de l'énergie mondiale depuis (1961 - 2020)"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(tidyselect)
library(countrycode)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Evolution de la production d'energie mondiale depuis 1961

```{r fig.width=15}
energy<-read_delim("owid-energy-data__OWID.csv")

seqTp_energy <- energy |> 
  select(1:3,contains("consumption")) |>
  filter(year >= 1961 & year <= 2020) |> 
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation") |> 
  mutate(types = case_when(str_detect(type_energie,"coal|gas|oil")~"fossil_fuel_consumption",
                                 str_detect(type_energie,"nuclear|biofuel|hydro|other_renewable|solar|wind")~"low_carbon_consumption",
                           TRUE~NA_character_)) |> 
   mutate(sources_energy = case_when(str_detect(type_energie,"biofuel")~"biofuel",
                                      str_detect(type_energie,"coal")~"coal",
                                      str_detect(type_energie,"wind")~"wind",
                                      str_detect(type_energie,"gas")~"gas",
                                      str_detect(type_energie,"hydro")~"hydro",
                                      str_detect(type_energie,"solar")~"solar",
                                    str_detect(type_energie,"nuclear")~"nuclear",
                                    str_detect(type_energie,"oil")~"oil",
                                    str_detect(type_energie,"other_renewable")~"other_renewable_consumption"
                                    ))
energy_source<- seqTp_energy |> 
  filter(country=="World") |> 
  drop_na(types) |> 
  rename(annee='year')

ggplot(energy_source )+
  aes(annee,consommation,colour=sources_energy, fill=sources_energy)+
  geom_col()+
  facet_grid(~types)+
     labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
     )


```

Column {data-width=450}
-----------------------------------------------------------------------

###  Evolution de la production de nourriture mondiale depuis 1961

```{r fig.width=10}


food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |> 
  select(-ends_with("F")) |> 
  pivot_longer(cols=Y1961:Y2020,
               names_to="annee",
               values_to="valeur") |> 
  mutate(annee=parse_number(annee))

food_world<-food |> 
  filter(Area=="World",
         Element=="Production") |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))

ggplot(food_world)+
  aes(annee,valeur,colour=Item)+
  geom_point()+
  geom_line()+
  theme(axis.text.x=element_text(size=12,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=12,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

```

### Evolution de la population mondiale depuis 1961

```{r fig.width=8 }
population<- read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv", skip=16,  na="...")
population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx", skip = 16, na="...") |>
  select(1:3, Type,"1950":"2020" )  |>
  pivot_longer(cols=5:75,
               names_to ="annee",
               values_to = "population") |>
  mutate(population=population*1000) |>
  rename(region=3)

population_monde <-population |>
  filter(Type=="World") |>
  filter(annee >= 1961) |>
  mutate(annee=(as.numeric(annee)))

ggplot(population_monde) +
  aes(annee, population) +
  geom_point() +
  geom_line(aes(group=1)) +
  scale_x_continuous( trans='log10') +
  scale_y_continuous(labels=function(x) {
    format(x,scientific=TRUE,
           big.mark=" ")
  })+
  theme(axis.text.x=element_text(size=12,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=12,
                                 
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

```

