---
title: "Séquences Shiny - Formation CEFIM juin 2022"
author: "Oswaldo Forey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(tidyverse)
library(lubridate)
library(readxl)
library(countrycode)

```


```{r}
population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx", skip = 16, na="...") |>
  select(1:3, Type,"1950":"2020" )  |>
  pivot_longer(cols=5:75,
               names_to ="annee",
               values_to = "population") |>
  mutate(population=population*1000) |>
  rename(region=3)

population_country<-population |>
  filter(annee >= 1961) |>
  select(annee, population, region) |>
  mutate(country=countrycode(region, origin = "country.name", destination = "country.name")) |>
  drop_na(country) |>
  mutate(annee=(as.numeric(annee)))

#la carte 
world_map <- map_data("world") |> 
  mutate(country=countrycode(region, origin = "country.name", destination = "country.name"))

#fusionner les données lat/long avec les données gapminder

population_carte <- world_map |>
  mutate(group=factor(group),
         region=factor(region)) |> 
  full_join(population_country,by="country")

test_population <- population_country |> 
  distinct(country)

# carte choroplethe

ggplot(population_carte)+
  aes(long,lat,group=group)+
  geom_polygon(aes(fill=population),colour="black")


test_population <- population_country |> 
  distinct(country)

ggplot(population_country |>
         filter(country=='France'))+
  aes(annee, population , fill=country)+
  geom_col()


#Partie food

food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |>
  select(-ends_with("F")) |>
  pivot_longer(cols=Y1961:Y2020,
               names_to="annee",
               values_to="Production_nourriture") |>
  mutate(annee=parse_number(annee))

food_country <-food |>
  filter(Element=="Production") |>
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary")) |>
  rename(country=Area)

test_food_country <- food_country |> 
  distinct(country)

  #rename(region=3)
ggplot(food_country |>
         filter(country=='France'))+
  aes(annee, Production_nourriture , fill=country)+
  geom_col()

#Partie Energie
energy<-read_delim("owid-energy-data__OWID.csv")
seqTp_energy <- energy |>
  select(1:3,contains("consumption")) |>
  filter(year >= 1961 & year <= 2020) |>
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation") |>
  mutate(types = case_when(str_detect(type_energie,"coal|gas|oil")~"fossil_fuel_consumption",
                                 str_detect(type_energie,"nuclear|biofuel|hydro|other_renewable|solar|wind")~"low_carbon_consumption",
                           TRUE~NA_character_)) |>
   mutate(sources_energy = case_when(str_detect(type_energie,"biofuel")~"biofuel",
                                      str_detect(type_energie,"coal")~"coal",
                                      str_detect(type_energie,"wind")~"wind",
                                      str_detect(type_energie,"gas")~"gas",
                                      str_detect(type_energie,"hydro")~"hydro",
                                      str_detect(type_energie,"solar")~"solar",
                                    str_detect(type_energie,"nuclear")~"nuclear",
                                    str_detect(type_energie,"oil")~"oil",
                                    str_detect(type_energie,"other_renewable")~"other_renewable_consumption"
                                    ))
energy_country<- seqTp_energy |>
  rename(annee="year") |>
  mutate(annee=(as.numeric(annee))) |>
  drop_na(types)

test_energy_country <- energy_country |> 
  distinct(country)

ggplot(energy_country|>
         filter(country=='France'))+
  aes(annee,consommation,fill=country)+
  geom_col()+
  facet_grid(~types)+
     labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))



ui <- fluidPage(
   titlePanel("Evolution de la population par pays depuis (1961 - 2020)"),
    sidebarLayout(
   sidebarPanel(
      selectInput(inputId="PAYS",
                  label="Choisissez un pays",
                   choices=population_country |>
                    distinct(country) |>
                    arrange(country) |>
                    pull()
       ),
      selectInput(inputId="ANNEE",
                  label="Choisissez une annee",
                   choices=population_country |>
                    distinct(annee) |>
                    arrange(annee) |>
                    pull()
       ),
      radioButtons(inputId="VARIABLE",
                   label="Choisissez une variable",
                   choices=c("Population",
                             "Nourriture",
                             "Energie")
                   )
     ),
     mainPanel(
       column(width=4,
              wellPanel(
                titlePanel("Evolution de la nourriture"),
                plotOutput(outputId="GRAPHIQUEN")
              )
       ),
       column(width=4,
              wellPanel(
                titlePanel("Evolution de la population"),
                plotOutput(outputId="GRAPHIQUEP")
              )
        ),
        column(width=4,
              wellPanel(
                titlePanel("Evolution de l'energie"),
                plotOutput(outputId="GRAPHIQUEE")
              )
        ),
       mainPanel(
         column(width=5,
             wellPanel(
               titlePanel("Carte population"),
               plotOutput(outputId="GRAPHIQUEPP")
             )
       )
       )
     )
    )
)
server <- function(input, output, session) {
  filtre<-reactive({
    population_country |>
      filter(country==input$PAYS )
  })
  output$GRAPHIQUEP<-renderPlot({
      ggplot(filtre())+
      aes(annee, population , fill=country)+
      geom_col()
  })
  
  output$GRAPHIQUEN<-renderPlot({
      ggplot(food_country |>
        filter(country==input$PAYS))+
      aes(annee, Production_nourriture, fill=country)+
      geom_col()
  })
  #Partie_Energie
  output$GRAPHIQUEE<-renderPlot({
      ggplot(energy_country |>
        filter(country == input$PAYS ))+
      aes(annee,consommation, fill=country)+
      geom_col()+
        facet_grid(~types)
  })
    output$GRAPHIQUEPP <- renderPlot({

     ggplot(population_carte)+
        aes(long,lat,group=group)+
        geom_polygon(aes(fill=population),colour="black")

    })
}

shinyApp(ui, server)
```

