---
title: "TP"
author: "Oswaldo Forey"
date: '2022-06-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(countrycode)


```

# ANALYSE MONDIALE

## POPULATION 

```{r POPULATION CHARGEMENT}

population<- read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv", skip=16,  na="...")
population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx", skip = 16, na="...") |>
  select(1:3, Type,"1950":"2020" )  |>
  pivot_longer(cols=5:75,
               names_to ="annee",
               values_to = "population") |>
  mutate(population=population*1000) |>
  rename(region=3)

population_monde <-population |>
  filter(Type=="World") |>
  filter(annee >= 1961) |>
  mutate(annee=(as.numeric(annee)))

ggplot(population_monde) +
  aes(annee, population) +
  geom_point() +
  geom_line(aes(group=1)) +
  scale_x_continuous( trans='log10') +
  scale_y_continuous(labels=function(x) {
    format(x,scientific=FALSE,
           big.mark=" ")
  })



```

```{r POPULATION GRAPHIQUE}

# on ne filtre que les données du monde

population_monde<-population |> 
  filter(Type=="World")

ggplot(population_monde)+
  aes(annee,population)+
  geom_point()+
  geom_line(aes(group=1))+
  scale_y_continuous(labels=function(x) {
    format(x,scientific=FALSE,
           big.mark=" ")
  })
```




## ENERGIE

```{r   ERGIE CHARGEMENT}

library(tidyselect)

energy<-read_delim("owid-energy-data__OWID.csv")

seqTp_energy <- energy |> 
  select(1:3,contains("consumption")) |>
  filter(year >= 1961 & year <= 2020) |> 
  pivot_longer(cols=4:16,
               names_to="type_energie",
               values_to="consommation") |> 
  mutate(types = case_when(str_detect(type_energie,"coal|gas|oil")~"fossil_fuel_consumption",
                                 str_detect(type_energie,"nuclear|biofuel|hydro|other_renewable|solar|wind")~"low_carbon_consumption",
                           TRUE~NA_character_)) |> 
   mutate(sources_energy = case_when(str_detect(type_energie,"biofuel")~"biofuel",
                                      str_detect(type_energie,"coal")~"coal",
                                      str_detect(type_energie,"wind")~"wind",
                                      str_detect(type_energie,"gas")~"gas",
                                      str_detect(type_energie,"hydro")~"hydro",
                                      str_detect(type_energie,"solar")~"solar",
                                    str_detect(type_energie,"nuclear")~"nuclear",
                                    str_detect(type_energie,"oil")~"oil",
                                    str_detect(type_energie,"other_renewable")~"other_renewable_consumption"
                                    ))


test <- seqTp_energy |> 
  filter(year==1961 & country == "Afghanistan")


seqTp_energy |> distinct(type_energie)

```

```{r ENERGIE GRAPHIQUE Types}

energy_source<- seqTp_energy |> 
  filter(country=="World") |> 
  drop_na(types)

ggplot(energy_source )+
  aes(year,consommation,colour=sources_energy, fill=sources_energy)+
  geom_col()+
  #geom_point()+
  facet_grid(~types)

```

```{r ENERGIE GRAPHIQUE Sources}

# 
# ggplot(energy_source)+
#   
#   aes(year,consommation,colour=sources_energy)+
#   geom_col()

```

## NOURRITURE

```{r NOURRITURE CHARGEMENT}

guess_encoding("Production_Crops_Livestock_E_All_Data.csv")

food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |> 
  select(-ends_with("F")) |> 
  pivot_longer(cols=Y1961:Y2020,
               names_to="annee",
               values_to="valeur") |> 
  mutate(annee=parse_number(annee))

# exploration des colonnes caractérisant la production

food_items<-food |> distinct(Item)

food |> distinct(Element)

```

```{r GRAPHIQUE STAPLE FOOD}

# on ne conserve que les monde, que la production (colonne Element) et que la nourriture de base (finissant par Total et Primary dans colonne Item)

food_world<-food |> 
  filter(Area=="World",
         Element=="Production") |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))

ggplot(food_world)+
  aes(annee,valeur,colour=Item)+
  geom_point()+
  geom_line()



```



# ANALYSE PAR CONTINENT
## Population
```{r}
# exploration des colonnes caractérisant la production
population |> distinct(Type)

population |> distinct(region)

population_continent<-population |>
  select(annee, population, region) |> 
  mutate(continent=countrycode(region, origin = "country.name", destination = "continent"))

#on filtre que les données des continent
population_continent |>
#distinct type of country country_type<- population |> distinct(Type)
  
  filter(annee >= 1961) |>
  mutate(annee=(as.numeric(annee)))

ggplot(population_continent |> 
         mutate(annee=(as.numeric(annee))) |> 
         drop_na(continent)) +
  aes(annee, population,fill=continent) +
  geom_col()+
  scale_x_continuous( trans='log10') +
  scale_y_continuous(labels=function(x) {
    format(x,scientific=FALSE,
           big.mark=" ")
    
  })


```

## Energie
```{r}
energy_continent<- seqTp_energy |>
  mutate(continent=countrycode(country, origin = "country.name", destination = "continent"))|>
  rename(annee="year") |> 
  mutate(annee=(as.numeric(annee)))
  drop_na(continent) |> 
  drop_na(types)
    
#pour véréfier na dans continent
test_continent <- energy_continent |> 
  distinct(continent,country)
  
#vérifier les na dans types
test_continent_types  <- energy_continent |> 
  distinct(type_energie,sources_energy,types) 


ggplot(energy_continent )+
  aes(annee,consommation,fill=continent)+
  geom_col()+
  facet_grid(~types)+
     labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

ggplot(energy_continent )+
  aes(annee,consommation,fill=sources_energy)+
  geom_col()+
  facet_grid(~continent)+
  labs(x="Annee", y="Consommation (TWh)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

```

## Nourriture
```{r}

food<-read_delim("Production_Crops_Livestock_E_All_Data.csv",
                 locale=locale(encoding="ISO-8859-1")) |> 
  select(-ends_with("F")) |> 
  pivot_longer(cols=Y1961:Y2020,
               names_to="annee",
               values_to="Production_norriture") |> 
  mutate(annee=parse_number(annee)) |> 
  mutate(continent=countrycode(Area, origin = "country.name", destination = "continent")) |> 
  drop_na(continent)

food_continent <-food |> 
  filter(Element=="Production") |> 
  filter(str_detect(Item,"Total")|str_detect(Item,"Primary"))

ggplot(food_continent)+
  aes(annee,Production_norriture,colour=continent, fill=continent)+
  geom_col()+
  labs(x="Annee", y="Production de norriture (tonnes)")+
  theme(axis.text.x=element_text(size=12,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=12,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))


ggplot(food_continent )+
  aes(annee,Production_norriture,fill=Item)+
  geom_col()+
  facet_grid(~continent)+
  labs(x="Annee", y="Production de norriture (tonnes)")+
  theme(axis.text.x=element_text(size=14,
                                 angle=45,
                                 hjust=1,
                                 vjust=1),
        axis.text.y=element_text(size=14,
                                 hjust=1,
                                 vjust=1),
        strip.text.x=element_text(colour="black",
                                  face="bold"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

#distinct les aera

food_distinct <- food |> 
  distinct(Area)

```
# ANALYSE PAR PAYS

## Population
```{r POPULATION CHARGEMENT}


population<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx", skip = 16, na="...") |>
  select(1:3, Type,"1950":"2020" )  |>
  pivot_longer(cols=5:75,
               names_to ="annee",
               values_to = "population") |>
  mutate(population=population*1000) |>
  rename(region=3)

population_country<-population |>
  filter(annee >= 1961) |> 
  select(annee, population, region) |> 
  mutate(country=countrycode(region, origin = "country.name", destination = "country.name")) |> 
  drop_na(country) |> 
  mutate(annee=(as.numeric(annee)))

#Vérifier les differents payes
# test_country <- population_country |> 
#   distinct(country) |> 
#   drop_na(country)

ggplot(population_country)+
  aes(annee, population , fill=country)+
  geom_col()



```

## Energie
## Nourriture

